# Pandas

## Pandas 패키지

    - Index를 가진 자료형인 R의 data.frame 자료형을 Python에서 구현
    - 참고자료
        - http://pandas.pydata.org/
        - http://pandas.pydata.org/pandas-docs/stable/10min.html
            - http://pandas.pydata.org/pandas-docs/stable/tutorials.html
            
## Pandas 자료형

    - Series
        - 시계열 데이터
        - Index를 가지는 1차원 Numpy Array
    - DataFrame
        - 복수 필드 시계열 데이터 또는 테이블 데이터
        - Index를 가지는 2차원 Numpy Array
    - Index
        - Label : 각각의 Row/Column에 대한 이름
        - Name : 인덱스 자체에 대한 이름
    
    - https://docs.google.com/drawings/d/12FKb94RlpNp7hZNndpnLxmdMJn3FoLfGwkUAh33OmOw/pub?w=602&h=446

### Series

명시적인 Index를 가지지 않는 Series

In [1]:
import pandas as pd

In [2]:
s = pd.Series([4, 7, -5, 4])
s

0    4
1    7
2   -5
3    4
dtype: int64

In [3]:
s.values

array([ 4,  7, -5,  4])

In [4]:
type(s.values)

numpy.ndarray

In [5]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
type(s.index)

pandas.indexes.range.RangeIndex

### Vectorized Operation

In [7]:
s * 2

0     8
1    14
2   -10
3     8
dtype: int64

In [8]:
import numpy as np

In [9]:
np.exp(s)

0      54.598150
1    1096.633158
2       0.006738
3      54.598150
dtype: float64

### 명시적인 Index를 가지는 Series

    - 생성시 index 인수로 index 지정
    - index 원소는 각 데이터에 대한 key 역할을 하는 Label
    - dict

In [10]:
s2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [11]:
s2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
s2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

### Series Indexing 1: Label Indexing

    - Single Label
    - Label Slicing
        - 마지막 원소 포함
    - Label을 원소로 가지는 Label (Label을 사용한 List Fancy Indexing)
        - 주어진 순서대로 재배열

In [13]:
s2['a']

-5

In [14]:
s2["b":"c"]

b    7
a   -5
c    3
dtype: int64

In [15]:
s2[['a', 'b']]

a   -5
b    7
dtype: int64

### Series Indexing 2: Integer Indexing

    - Single Integer
    - Integer Slicing
        - 마지막 원소를 포함하지 않는 일반적인 Slicing
    - Integer List Indexing (List Fancy Indexing)
    - Boolearn Fancy Indexing

In [16]:
s2[2]

-5

In [17]:
s2[1:4]

b    7
a   -5
c    3
dtype: int64

In [18]:
s2[[2, 1]]

a   -5
b    7
dtype: int64

In [19]:
s2[s2 > 0]

d    4
b    7
c    3
dtype: int64

### dict 연산

In [20]:
"a" in s2, "e" in s2

(True, False)

In [21]:
for k, v in s2.iteritems():
    print(k, v)

d 4
b 7
a -5
c 3


In [22]:
s2["d":"a"]

d    4
b    7
a   -5
dtype: int64

### dict 데이터를 이용한 Series 생성

In [23]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [24]:
s3 = pd.Series(sdata)
s3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [25]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
s4 = pd.Series(sdata, index=states)
s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isnull(s4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(s4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
s4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
s4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

### Index 기준 연산

In [30]:
print(s3.values, s4.values)

[35000 16000 71000  5000] [    nan  35000.  16000.  71000.]


In [31]:
s3.values + s4.values

array([    nan,  51000.,  87000.,  76000.])

In [32]:
s3 + s4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

### Index 이름

In [33]:
s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
s4.name = "population"
s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
s4.index.name = "state"
s4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### Index 변경

In [36]:
s

0    4
1    7
2   -5
3    4
dtype: int64

In [37]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [38]:
s.index = ['Andrew','Sonia','Veronica','Jayden']

In [39]:
s

Andrew      4
Sonia       7
Veronica   -5
Jayden      4
dtype: int64

In [40]:
s.index

Index(['Andrew', 'Sonia', 'Veronica', 'Jayden'], dtype='object')

### DataFrame

    - Multi-Series
        - 동일한 Row 인덱스를 사용하는 복수 Series
        - Series를 Value로 가지는 dict
    - 2차원 행렬
        - DataFrame을 행렬로 생각하면 각 Series는 행렬의 Column의 역할
        - (Row) Index와 Column Index를 가진다.
    - Numpy Array와 차이점
        - 각 Column(Series)마다 type이 달라도 된다.

In [41]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
}
df = pd.DataFrame(data)
df

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [42]:
pd.DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [43]:
df.dtypes

pop      float64
state     object
year       int64
dtype: object

### 명시적인 Column/Row Index를 가지는 DataFrame

In [44]:
df2 = pd.DataFrame(data, 
                   columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

### Single Column Access

In [45]:
df["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [46]:
type(df["state"])

pandas.core.series.Series

In [47]:
df.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

### Column Data Update

In [48]:
df2['debt'] = 16.5
df2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [49]:
df2['debt'] = np.arange(5)
df2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [50]:
df2['debt'] = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

### Add Column

In [51]:
df2['eastern'] = df2.state == 'Ohio'
df2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

### Delete Column

In [52]:
del df2['eastern']
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

### inplace 옵션

    - 함수/메소드는 두 가지 종류
        - 그 객체 자체를 변형
        - 해당 객체는 그대로 두고 변형된 새로운 객체를 출력
    - DataFrame 메소드 대부분은 inplace 옵션을 가짐
        - inplace = True 이면 출력을 None으로 하고 객체 자체를 변형
        - inplace = False 이면 객체 자체는 보존하고 변형된 새로운 객체를 출력

In [53]:
x = [3, 6, 1, 4]
sorted(x)

[1, 3, 4, 6]

In [54]:
x

[3, 6, 1, 4]

In [55]:
x.sort()
x

[1, 3, 4, 6]

### drop 메소드를 사용한 Row/Column 삭제

    - del 함수
        - inplace 연산
    - drop 메소드
        - 삭제된 Series/DataFrame 출력
        - Series는 Row 삭제
        - DataFrame은 axis 인수로 Row/Column 선택
            - axis = 0 (디폴트): Row
            - axis = 1 : Column

In [56]:
s = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
s

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [57]:
s2 = s.drop('c')
s2

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [58]:
s

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [59]:
s.drop(["b", "c"])

a    0.0
d    3.0
e    4.0
dtype: float64

In [60]:
df = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [61]:
df.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [62]:
df.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [63]:
df.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Nested dict를 사용한 DataFrame 생성

In [64]:
pop = {
    'Nevada': {
        2001: 2.4, 
        2002: 2.9
    },
    'Ohio': {
        2000: 1.5, 
        2001: 1.7, 
        2002: 3.6
    }
}

In [65]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [66]:
df3 = pd.DataFrame(pop)
df3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

### Series dict를 사용한 DataFrame 생성

In [67]:
pdata = {
    'Ohio': df3['Ohio'][:-1],
    'Nevada': df3['Nevada'][:2]
}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

### NumPy array로 변환

In [68]:
df3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [69]:
df2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### DataFrame의 Column Indexing

    - Single Label key
    - Single Label attribute
    - Label List Fancy Indexing

In [70]:
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [71]:
df2["year"]

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [72]:
df2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [73]:
df2[["state", "debt", "year"]]

state  debt  year
one      Ohio   NaN  2000
two      Ohio  -1.2  2001
three    Ohio   NaN  2002
four   Nevada  -1.5  2001
five   Nevada  -1.7  2002

In [74]:
df2[["year"]]

year
one    2000
two    2001
three  2002
four   2001
five   2002